services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  web:
    image: nginx:stable
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  node:
    image: node:20
    container_name: laravel_node
    ports:
      - "5174:5173"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel

networks:
  laravel:
